name: generate-deb-packages-aws

on:
  push:
    branches:
      - 'release/2023.05'
  pull_request:
    branches:
      - 'release/2023.05'

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.EC2_ON_DEMAND_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.EC2_ON_DEMAND_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.EC2_ON_DEMAND_AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: esteve/ec2-github-runner@Optionally-execute-runner-as-a-service
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN_MFC }}
          ec2-image-id: ami-044ac2f64df582e8f
          ec2-instance-type: t3.xlarge
          subnet-id: subnet-4e5eb225
          security-group-id: sg-02780d120ee4d06e1
          run-runner-as-service: true
          run-runner-as-user: ubuntu
  generate-deb-packages-aws:
    name: Build Debian packages for Autoware (Humble)
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}
    timeout-minutes: 1440
    permissions:
      deployments: write
      contents: write
      statuses: write
      actions: write
      checks: read
    steps:
      - name: Remove unattended-upgrades
        run: sudo apt-get remove -y --purge unattended-upgrades
      - name: Build Debian packages
        uses: jspricke/ros-deb-builder-action@main
        with:
          ROSDEP_SOURCE: yaml https://s3.amazonaws.com/autonomoustuff-repo/autonomoustuff-public-humble.yaml
          SBUILD_CONF: $extra_repositories = ["deb [trusted=yes] https://s3.amazonaws.com/autonomoustuff-repo/ jammy main"];
          DEB_DISTRO: jammy
          ROS_DISTRO: humble
          REPOS_FILE: https://raw.githubusercontent.com/autowarefoundation/autoware/release/2023.05/autoware.repos
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
          SKIP_PACKAGES: velodyne_pointcloud velodyne_msgs velodyne_driver traffic_light_classifier traffic_light_ssd_fine_detector tensorrt_yolo tier4_perception_launch autoware_launch
          PACKAGES_BRANCH: jammy-humble-release/2023.05
          GIT_LFS: true
  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner
      - generate-deb-packages-aws
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.EC2_ON_DEMAND_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.EC2_ON_DEMAND_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.EC2_ON_DEMAND_AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN_MFC }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
