
name: generate-deb-packages-aws

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: generate-deb-packages # only one job can run at a time
  cancel-in-progress: true

jobs:
  generate-debian-packages:
    name: "Generate Debian packages"
    uses: ./.github/workflows/generate-deb-packages-aws-reusable.yaml
    with:
      colcon-defaults-file: colcon-skip-cuda.yml
      packages-branch: jammy-humble-main
      artifacts-upload-name: no-cuda-debian-packages

  generate-debian-packages-cuda:
    name: "Generate CUDA Debian packages"
    uses: ./.github/workflows/generate-deb-packages-aws-reusable.yaml
    needs: generate-debian-packages
    with:
      colcon-defaults-file: colcon-only-cuda.yml
      packages-branch: jammy-humble-main-cuda
      artifacts-download-name: no-cuda-debian-packages
