name: generate-deb-packages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-deb-packages:
    runs-on: ubuntu-22.04
    steps:
      - uses: jspricke/ros-deb-builder-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ROS_DISTRO: humble
          DEB_DISTRO: jammy
