
name: generate-deb-packages-aws

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: generate-deb-packages # only one job can run at a time
  cancel-in-progress: true

jobs:
  generate-deb-packages-aws:
    name: "Build Debian packages for Autoware (Humble)"
    runs-on: [self-hosted, Linux, X64, generate-deb-pkgs]
    timeout-minutes: 5760
    permissions:
      deployments: write
      contents: write
      statuses: write
      actions: write
      checks: read
    steps:
      - name: "Remove unattended-upgrades"
        run: sudo apt-get remove -y --purge unattended-upgrades
      - name: "Clean up build environment"
        run: rm -rfv "$HOME/.cache/ccache"
      - name: "Setup ROS"
        uses: ros-tooling/setup-ros@v0.7
      - name: "Check if packages should be pushed to the repo"
        run: |
          if [[ "${{ startsWith(github.ref, 'refs/heads/') && !startsWith(github.ref, 'refs/pull/')}}" == "true" ]]; then
            echo "push_packages=true" >> $GITHUB_ENV
            echo "gh_personal_access_token_mfc=${{ secrets.GH_PERSONAL_ACCESS_TOKEN_MFC }}" >> $GITHUB_ENV
          else
            echo "push_packages=false" >> $GITHUB_ENV
            echo "gh_personal_access_token_mfc=" >> $GITHUB_ENV
          fi
      - name: "Build Debian packages (pushing packages to repository: ${{ env.push_packages }})"
        uses: jspricke/ros-deb-builder-action@main
        with:
          ROSDEP_SOURCE: yaml https://s3.amazonaws.com/autonomoustuff-repo/autonomoustuff-public-humble.yaml
          SBUILD_CONF: $extra_repositories = ["deb [trusted=yes] https://s3.amazonaws.com/autonomoustuff-repo/ jammy main"];
          DEB_DISTRO: jammy
          ROS_DISTRO: humble
          REPOS_FILE: sources.repos
          GITHUB_TOKEN: ${{ env.gh_personal_access_token_mfc }}
          SQUASH_HISTORY: true
          PACKAGES_BRANCH: jammy-humble-main
          GIT_LFS: true
          COLCON_DEFAULTS_FILE: colcon-skip-cuda.yml

      - name: "Tar artifacts"
        run: tar -cvf apt_repo.tar apt_repo

      - name: "Share Debian packages with the CUDA-only job"
        uses: actions/upload-artifact@v4
        with:
          name: no-cuda-debian-packages
          path: apt_repo.tar
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
